stages:
  load_data:
    cmd: python src/stage_01_load_and_save_data.py --config=params.yaml
    deps:
      - src/stage_01_load_and_save_data.py
    params:
      - data_source.drive_source
      - artifacts.raw_local_data
    outs:
      - artifacts/raw_local_data_dir/data.csv

  split_data:
    cmd: python src/stage_02_preprocess.py --config=params.yaml
    deps:
      - src/stage_02_preprocess.py
      - artifacts/raw_local_data_dir/data.csv
    params:
      - artifacts.raw_local_data
      - artifacts.preprocess_data.processed_data_dir
      - artifacts.preprocess_data.train_path
    outs:
      - artifacts/processed_data/train.csv

  train:
    cmd: python src/stage_03_train.py --config=params.yaml
    deps:
      - src/stage_03_train.py
      - artifacts/processed_data/train.csv
    params:
      - base.random_state
      - artifacts.preprocess_data.processed_data_dir
    outs:
      - artifacts/saved_models/model.joblib 

#   evaluate:
#     cmd: python src/stage_04_evaluate.py --config=params.yaml
#     deps:
#       - src/stage_04_evaluate.py
#       - artifacts/processed_data/test.csv
#     params:
#       - artifacts.split_data.processed_data_dir
#       - artifacts.split_data.test_path
#       - artifacts.model_path
#       - base.target_col
#       - artifacts.reports.scores
#     metrics:
#       - artifacts/report/scores.json:
#           cache: false
    